name: check
on:
  push:
  pull_request:


concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
#          - "3.12.0" # TODO: check again once eventlet fixes their issues https://github.com/eventlet/eventlet/pull/797/files
          - "3.11.6"
          - "3.10.13"
          - "3.9.18"
          - "3.8.18"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install requirements
        run: python -m pip install -r requirements/ci_requirements.txt
      - name: Setup test suite
        run: tox -vv --notest
      - name: Run test suite
        run: tox --skip-pkg-install